import { useEffect } from 'react'
import { createPortal } from 'react-dom'
import type { GameCatalog } from '../../../api/types'
import { Button } from '../../../components/ui'
import animalDuo from '../../../assets/characters/noopi-animal-duo.png'
import citizenCharacter from '../../../assets/characters/noopi-citizen-dog.png'
import catCharacter from '../../../assets/characters/noopi-cat.png'
import mafiaCharacter from '../../../assets/characters/noopi-mafia-cat-game-choice.png'

export function MafiaGameGuide({ game, onClose, onAction }: { game: GameCatalog['games'][number]; onClose: () => void; onAction: () => void }) {
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose])
  return createPortal(<div className="dialogBackdrop gameGuideBackdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="gameGuideDialog mafiaGameGuideDialog" role="dialog" aria-modal="true" aria-labelledby="mafia-guide-title" aria-describedby="mafia-guide-summary"><header className="gameGuideHeader"><div><p>NOOPI GAME GUIDE</p><h2 id="mafia-guide-title">{game.name}</h2></div><button type="button" onClick={onClose} aria-label="게임 방법 닫기">×</button></header><p className="gameGuideSummary" id="mafia-guide-summary">밤에는 정체를 숨기고 능력을 사용하고, 낮에는 얼굴을 마주 보며 마피아를 찾아내세요.</p><div className="gameGuideMeta"><span>👥 {game.minPlayers}–{game.maxPlayers}명</span><span>🎭 역할 자동 배정</span></div><ol className="gameGuideSteps mafiaGuideSteps"><li><div className="guideScene mafiaGuideSceneRole" aria-hidden><img src={mafiaCharacter} alt="" /><i>?</i></div><div><small>STEP 1</small><h3>나만의 역할을 확인해요</h3><p>마피아·경찰·의사·시민 중 하나가 돼요. 마피아가 여러 명이면 서로를 알 수 있어요.</p></div></li><li><div className="guideScene mafiaGuideSceneNight" aria-hidden><img src={catCharacter} alt="" /><i>☾</i></div><div><small>STEP 2</small><h3>첫 번째 밤이 찾아와요</h3><p>경찰은 한 명을 조사하고 시민은 의심되는 한 명을 골라요. 첫날에는 공격과 치료가 없어요.</p></div></li><li><div className="guideScene mafiaGuideSceneAction" aria-hidden><img src={mafiaCharacter} alt="" /><i>!</i></div><div><small>STEP 3</small><h3>밤마다 능력을 사용해요</h3><p>마피아는 공격하고, 경찰은 조사하고, 의사는 치료해요. 시민은 마음속 의심을 남깁니다.</p></div></li><li><div className="guideScene mafiaGuideSceneTalk" aria-hidden><img src={animalDuo} alt="" /><i>···</i></div><div><small>STEP 4</small><h3>낮에는 함께 토론해요</h3><p>밤의 사망 결과와 내가 받은 의심 수를 보고, 서로의 말과 표정을 살펴보세요.</p></div></li><li><div className="guideScene mafiaGuideSceneVote" aria-hidden><img src={citizenCharacter} alt="" /><i>✓</i></div><div><small>STEP 5</small><h3>비밀투표로 처형해요</h3><p>생존자 모두가 한 명에게 투표해요. 마피아를 모두 찾으면 시민팀, 마피아가 시민팀만큼 남으면 마피아팀 승리!</p></div></li></ol><div className="gameGuideTip mafiaGuideTip"><b>누피의 팁</b><span>휴대폰에 나온 비밀은 나만 보고, 토론할 때는 화면보다 친구들의 표정을 살펴보세요!</span></div><Button className="gameGuideStart" onClick={onAction}>시작하기</Button></section></div>, document.body)
}
